version: '3.8'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_SECRET}
    networks:
      - pi #a name for the Cloudflare Network
    restart: unless-stopped
    
  traefik:
    image: 'traefik:2.3'
    container_name: 'traefik'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '8080:8080'
      - '8000:8000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/traefik.toml:/traefik.toml'
    networks:
      - pi

  whoami:
    image: 'traefik/whoami'
    restart: 'unless-stopped'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)'
      - 'traefik.http.services.whoami.loadbalancer.server.port=80'
    networks:
      - pi
  server:
    image: woodpeckerci/woodpecker-server:latest
    depends_on:
      - traefik
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=your_admin_user
      # other settings ...
      - WOODPECKER_HOST=https://cd.frederikbroth.dk
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=Ov23liJTqbpNVfRgnoCo
      - WOODPECKER_GITHUB_SECRET=${GITHUB_APP_SECRET}
    networks: 
      - pi # externally defined network, so that traefik can connect to the server
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/

    deploy:
      labels:
        - traefik.enable=true

        # web server
        - traefik.http.services.woodpecker-service.loadbalancer.server.port=8000


        - traefik.http.routers.woodpecker.rule=Host(`cd.frederikbroth.dk`)
        - traefik.http.routers.woodpecker.entrypoints=web
        - traefik.http.routers.woodpecker.service=woodpecker-service


        #  gRPC service
        - traefik.http.services.woodpecker-grpc.loadbalancer.server.port=9000
        - traefik.http.services.woodpecker-grpc.loadbalancer.server.scheme=h2c


        - traefik.http.routers.woodpecker-grpc.rule=Host(`woodpecker-grpc.frederikbroth.dk`)
        - traefik.http.routers.woodpecker-grpc.entrypoints=web
        - traefik.http.routers.woodpecker-grpc.service=woodpecker-grpc


volumes:
  woodpecker-server-data:
    driver: local
networks:
  pi: #a name for the Cloudflare Network
   external: true
