version: '3.8'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token CLOUDFLARE_SECRET
    networks:
      - pi #a name for the Cloudflare Network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - cloudflared
    ports:
      - "80:80"
    networks:
      - pi
    restart: unless-stopped
networks:
  pi: #a name for the Cloudflare Network
   external: true
