name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: Takes down Compose
      run: docker-compose down
    - name: Reapplys new docker compose
      run: docker-compose up
